# SPDX-FileCopyrightText: Copyright (c) 2020-2022 Polystat.org
# SPDX-License-Identifier: MIT

[files]
extend-exclude = [
  "**/src/test/resources/**",
]

[default]
extend-ignore-re = ['\\u\{[0-9A-Fa-f]+\}']

[default.extend-words]
fo = "fo"
scond = "scond"
ffor = "ffor"
iif = "iif"
INDEPEND = "INDEPEND"
