assets:
  settings.xml: yegor256/home#assets/polystat/settings.xml
merge:
  script: mvn clean install
deploy:
  script: mvn clean install
release:
  script: |-
    mvn versions:set "-DnewVersion=${tag}" -Dstyle.color=never
    git commit -am "${tag}"
    mvn clean install -Dinvoker.skip
    mvn clean deploy -Ppolystat -Psonatype --errors --settings ../settings.xml -Dstyle.color=never
