assets:
  settings.xml: yegor256/home#assets/polystat/settings.xml
  pubring.gpg: yegor256/home#assets/pubring.gpg
  secring.gpg: yegor256/home#assets/secring.gpg
merge:
  script: mvn clean install
deploy:
  script: mvn clean install
release:
  script: |-
    wget https://download.java.net/java/GA/jdk14.0.1/664493ef4a6946b186ff29eb326336a2/7/GPL/openjdk-14.0.1_linux-x64_bin.tar.gz
    wget https://dlcdn.apache.org/maven/maven-3/3.8.4/binaries/apache-maven-3.8.4-bin.tar.gz
    tar x -z < apache-maven-3.8.4-bin.tar.gz
    tar x -z < openjdk-14.0.1_linux-x64_bin.tar.gz
    PATH="$PWD/jdk-14.0.1/bin/:$PWD/apache-maven-3.8.4/bin/:$PATH"
    export JAVA_HOME="$PWD/jdk-14.0.1/"
    mvn versions:set "-DnewVersion=${tag}" -Dstyle.color=never
    git commit -am "${tag}"
    mvn clean install -Dinvoker.skip -DskipTests=true
    mvn clean deploy -Ppolystat -Psonatype --errors --settings ../settings.xml -Dstyle.color=never -DskipTests=true
    