name: Enabled tests counter

on:
  push

jobs:
  counter:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 14
        uses: actions/setup-java@v3
        with:
          java-version: '14'
          distribution: 'adopt'
          cache: 'maven'
      - name: Build counter
        run: mvn clean package -PEnabledTestsCounter -DskipTests -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
      - name: Rename counter
        run: cp transpiler/target/transpiler-*-jar-with-dependencies.jar counter.jar
      - name: Run counter
        run: java -jar counter.jar