# SPDX-FileCopyrightText: Copyright (c) 2020-2022 Polystat.org
# SPDX-License-Identifier: MIT

---
name: pdd
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  pdd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4.10
      - run: sudo apt-get update && sudo apt-get install -y libmagic-dev
      - run: gem install pdd -v 0.24.2
      - run: pdd --file=/dev/null
